### ISSUE TITLE
Issue game 

### ISSUE THREAD

**Issue by Justophil** [G0lG013/Unescapable#1]
this is a bug and a suggestion,
once you die you can rerun the game and respawn and continue your progress like nothing happen
![image](https://user-images.githubusercontent.com/89649491/145284040-e940cfe2-5bdc-429f-9186-38f0519a7e1e.png)
Plus you can respawn the boss by accident by going through the tank zombie stage back to the stage before and go back to the tank zombie  stage.

Plus you  can add a menu when the game ends where the player can restart the game or go back to the main menu.

Philip D.-

**Comment by RachelleBadua** [comment]
We completed the issue about the respawn where when you die, you go back to the menu and you can play again, and start a new game. We did not complete the issue about the tank zombie because we did not have enough time to do it, and we were working on other components of the game.
