### ISSUE TITLE
Issues and Comments

### ISSUE THREAD

**Issue by GoldyBlocksLOL** [G0lG013/Unescapable#2]
Hello,

I think the game is cool but I think it would really help if you indicate where to walk after defeating a room because I found myself banging into the edges of the world a lot trying to navigate the game.

Also, I'm pretty sure it's already been noted down but when you click the credits on the main menu, there's no way of going back.

Good luck with the rest of your game!! :)

Amanda

**Comment by RachelleBadua** [comment]
We completed the issue about where to go by adding walls to help navigate through the map and and know where the entrance of the next stage is. We also completed the issue about going to the menu when in instruction and credits by pressing shift to go back to the menu when in instructions and credits.
