### ISSUE TITLE
The character is bugging

### ISSUE THREAD

**Issue by Hussainamin10** [G0lG013/Unescapable#3]
When the character took damage the first time, he started bugging by moving left and right very fast at the bottom of the background after a few seconds he got hit. Also the keys to play the game are a little bit difficult to use. For example, if I want the character to move in another direction and at the same time shoot it is a little bit difficult.

Hussain Amin

**Comment by RachelleBadua** [comment]
We did not complete this issue about the character bugging because we did not have, and we were working on other components. We did complete the issue about shooting and moving.
