### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Vapidx4** [G0lG013/Unescapable#4]
Overall its a pretty good game but I've notice some issues.

I was kinda lost on where to go and was running into walls trying to find the entrance to the next stage. I've notice that I had to manually call the "addfence" method to easily figure out where I was going.

Goodluck on your game!

-Brandon

**Comment by RachelleBadua** [comment]
We have completed this issue by putting walls around the maps, so you can know the entrance to the next stage. We've change the fence to walls since it was more appropriate in our game.
